dpc-sdp/tide_webform

composer.json

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-995
1.

[SDPA-995] Lock webform version to 5.0.0-rc18

---

composer.json

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-472
Museum Content PR: https://github.com/dpc-sdp/museum-content-vicpol-vic-gov-au/pull/40
1.  Add patch to fix error in webform submissions that require token process

[SDPA-472] Add patch to fix error in webform submissions

---

composer.json
config/install/webform.webform.tide_webform_content_rating.yml
config/optional/jsonapi_extras.jsonapi_resource_config.webform--webform.yml
dev-init.sh
tests/behat/features/jsonapi.content_rating.feature
tide_webform.module

JIRA: https://digital-engagement.atlassian.net/browse/SDPA-1213
Related PRs:
* Tide Core: https://github.com/dpc-sdp/tide_core/pull/57
* Tide Media: https://github.com/dpc-sdp/tide_media/pull/19
* Tide API: https://github.com/dpc-sdp/tide_api/pull/28
* Tide Site: https://github.com/dpc-sdp/tide_site/pull/18
* Tide Webform: https://github.com/dpc-sdp/tide_webform/pull/21
* Tide News: https://github.com/dpc-sdp/tide_news/pull/14
* Tide Page: https://github.com/dpc-sdp/tide_page/pull/14
* Tide Event: https://github.com/dpc-sdp/tide_event/pull/24
* Tide Landing Page: https://github.com/dpc-sdp/tide_landing_page/pull/63
* Tide Monsido: https://github.com/dpc-sdp/tide_monsido/pull/13
* Tide Search: https://github.com/dpc-sdp/tide_search/pull/11
* Tide: https://github.com/dpc-sdp/tide/pull/39
* …

[SDPA-1213] Upgraded to JSON:API 2.0 and JSON:API Extras 3.3.

---

composer.json
config/optional/jsonapi_extras.jsonapi_resource_config.webform--webform.yml
tests/behat/features/fields.feature
tests/behat/features/jsonapi.content_rating.feature

JIRA: https://digital-engagement.atlassian.net/browse/SDPA-2192

Reverted entity_id aliasing in favour of JSON:API 2.x.

---

tests/behat/features/fields.feature

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Fixed behat test.

---

config/install/tide_webform.defaults.yml
src/Element/WebformPrivacyStatement.php
src/Plugin/WebformElement/WebformPrivacyStatement.php
tide_webform.install
tide_webform.module

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Added Privacy Statement element.

---

composer.json
tide_webform.install
tide_webform.module

https://digital-engagement.atlassian.net/browse/SDPA-2932

[SDPA-2932] update webform entities with default permission

---

tide_webform.install
tide_webform.module

https://digital-engagement.atlassian.net/browse/SDPA-2990

[SDPA-2290] webform access issue

---

tide_webform.module

https://digital-engagement.atlassian.net/projects/SDPA/issues/SDPA-3167
webform BE validation

[SDPA-3167] Added webform BE validation

---

composer.json

https://digital-engagement.atlassian.net/browse/SDPA-4217
1. update webform module to `8.x-5.11`
https://github.com/dpc-sdp/content-vic-gov-au/pull/858

[SDPA-4217] update webform module

---

composer.json

https://digital-engagement.atlassian.net/browse/SDPA-4217
1. https://github.com/dpc-sdp/tide_webform/pull/40

SDPA-4217 update webform module (#40)

---

composer.json
dev-tools.sh

https://digital-engagement.atlassian.net/browse/SDPA-4225
1. update drupal/webform to ^8.14

updates tide_webform to be compatible with D8.8.5

---

config/optional/block.block.tide_webform_content_rating.yml
tide_webform.install

https://digital-engagement.atlassian.net/browse/SDPA-4885
https://github.com/dpc-sdp/tide_landing_page/pull/121
https://github.com/dpc-sdp/tide_core/pull/201

[SDPA-4885] Fixes node clone layout issue

---

config/optional/block.block.tide_webform_content_rating.yml
tide_webform.install

Jira ticket - https://digital-engagement.atlassian.net/browse/SDPA-5160
Added a hook to remove the content rating block from the CMS. So the webform block does not show up in the CMS pages.

[SDPA-5160] Added hook to disable content rating webform block for cms.

---

composer.json

**JIRA issue:** https://digital-engagement.atlassian.net/browse/DDS-901
1.  Install third party webform libraries locally so that they don't need to be pulled from an external CDN (which is a security vulnerability).

[DDS-901] : Install third party libraries

---

config/install/tide_webform.defaults.yml
tide_webform.install

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-3771
1.  Changed Privacy Statement text to Drupal 9
2.  Updated hook
FE
To see the change: https://app.pr-901.vic-gov-au.sdp2.sdp.vic.gov.au/contact-us
BE

[SDPSUP-3771] Update Drupal Version

---

tide_webform.install

https://digital-vic.atlassian.net/browse/SRM-480
Hook was looking at the wrong value tree to update the setting

[SRM-480] Updated hook to add the webform setiings correctly.

---

composer.json
config/optional/system.action.webform_submission_make_process_action.yml
config/optional/system.action.webform_submission_make_unprocess_action.yml
src/Plugin/Action/WebformSubmissionProcessedAction.php
src/Plugin/Action/WebformSubmissionUnprocessedAction.php
src/TideWebformSubmissionListBuilder.php
tide_webform.install
tide_webform.module

**JIRA ISSUE:** https://digital-vic.atlassian.net/browse/SDPAP-6373
Changed labels on the process and unprocessed form submissions.
**Environment:** 
BE: https://nginx-php.pr-130.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/

[SDPAP-6373] Update labels for form submissions.

---

src/Plugin/jsonapi/FieldEnhancer/WebformConfirmationEnhancer.php
tide_webform.module

https://digital-vic.atlassian.net/browse/SDPAP-6895
1. Added webform submission enhancer to add the confirmation message field custom message to notes field on webform submission response.
2. Added mechanism to include any token used in the confirmation message field
3. The confirmation message field with token and the enhancer only works with hidden filed type

[SDPAP-6961] exposes api confirmation message

---

composer.json

https://digital-vic.atlassian.net/browse/SDPAP-7169
Add a patch in composer to fix the filter category. 
Link for testing purpose: https://nginx-php.pr-1497.content-vic.sdp4.sdp.vic.gov.au/admin/structure/webform?search=&category=ESTA&state=

[SDPAP-7169]adding patch to fix filter category

---

composer.json

**JIRA issue:**  https://digital-vic.atlassian.net/browse/SDPAP-6788
1.  Mark webform submission through batch process as processed.
2. Created a patch to change a static function for our use case in https://www.drupal.org/project/webform/issues/3348336

[SDPAP-6788] Export webform submission not marked as processed.

---

src/TideWebformSubmissionListBuilder.php
tide_webform.module

https://digital-vic.atlassian.net/browse/SDPAP-7717

[SDPAP-7717] Form submission with attachments

---

config/optional/webform.settings.yml
tide_webform.install

https://digital-vic.atlassian.net/browse/SDPAP-7450
Enables checkboxes field
*`webform_element` has also been enabled because of the dependency requirement.*

[SDPAP-7450] Enables checkboxes field

---

composer.json

simply update webform to 6.2.x

[SRM-710] Update drupal webform to 6.2.x

---

composer.json
config/optional/block.block.tide_webform_content_rating.yml
tide_webform.install

https://digital-vic.atlassian.net/browse/SRM-665
update to support Claro admin theme

[SRM-665] CLARO and CK5 upgrade

---

composer.json
dev-tools.sh

https://digital-vic.atlassian.net/browse/SDPAP-8014
The tool tip wasn't working for the webform module elements.
Updated library versions to match with the new changes made in the drupal webform composer library json. This resolves the conflict and 404 notices and tool tip starts working.
[tide_core](https://github.com/dpc-sdp/tide_core/pull/425)
[dev-tools](https://github.com/dpc-sdp/dev-tools/pull/102)
[Ansible hotfix task](https://github.com/dpc-sdp/sdp-ansible-upgrade/pull/147)
Testing PR - https://nginx-php.pr-1558.content-vic.sdp4.sdp.vic.gov.au/user/11438

[SDPAP-8014] Updated packages to fix the tool tip issue.
